app.name: MyApp

spring:
  session:
    store-type: redis

  # redis配置
    redis:
  # Redis服务器地址
        host: 10.3.10.217

  # Redis服务器连接端口
        port: 6379

  # Redis数据库索引（默认为0）
        database: 0

  # Redis服务器连接密码（默认为空）
        password:
  # 连接超时时间（毫秒）
        timeout: 0

        pool:
  # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
  # 连接池中的最大空闲连接
          pool.max-idle: 8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
  # 连接池中的最小空闲连接
          min-idle: 0



  ## 数据源配置

    datasource:
      url: jdbc:oracle:thin:@10.3.10.217:1521:frdb
      username: ryxpay
      password: aaa111
      driver-class-name: oracle.jdbc.OracleDriver



  # Mybatis 配置
  mybatis:
    typeAliasesPackage: com.wukp.boot.moudle.*.orm
    mapperLocations: classpath:mapper/*.xml

## a 数据源配置
a:
  datasource:
    url: jdbc:oracle:thin:ryxpay/ANT3F4DH1L2D@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.3.10.10)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.3.10.11)(PORT=1521))(LOAD_BALANCE=on)(FAILOVER=ON))(CONNECT_DATA=(SERVICE_NAME=hpaydb)))
    username: ryxpay
    password: ANT3F4DH1L2D
    driverClassName: oracle.jdbc.OracleDriver

## a 数据源配置
b:
  datasource:
    url: jdbc:oracle:thin:@10.3.10.217:1521:frdb
    username: ryxpay
    password: aaa111
    driverClassName: oracle.jdbc.OracleDriver


go:
wy: ${app.name}gougou

home:
  province: ZheJiang
  city: WenLing
  desc: dev I'm living in ${home.province} ${home.city}.


#tomcat 配置
server:
    port: 8088

#server.port = 8088
#server.session-timeout = 5
#server.tomcat.remote-ip-header = x-forwarded-for
#server.tomcat.protocol-header = x-forwarded-proto
#spring.http.encoding.charset = UTF-8
#server.tomcat.access-log-enabled = true
#server.tomcat.access-log-pattern = common

#属性可以根据运行环境自动读取不同的配置文件。例如将该属性定义为 dev 的话，Spring Boot 会额外从 application-dev.yml 文件中读取该环境的配置
#spring.profiles.active
